conditions: v1

git:
  depth: false


dist: xenial
cache: pip


language: python
python:
- "3.7"
- "3.6"
- "nightly"  # currently, it's 3.8-dev


install:
- python -m pip install --upgrade flit pip
- flit install

script:
- pytest


jobs:
  include:
  - name: Python 3.7 under Windows
    os: windows
    language: sh
    python: "3.7"
    before_install:
    - choco install python --version 3.7
    env:
      PATH: >-
        /c/Python37:/c/Python37/Scripts:$PATH

  - name: Publish dists to production PyPI
    stage: Publish dists to PYPI
    if: tag IS present
    python: "3.7"
    script:
    - flit build
    before_deploy:
    # Add an empty setup.py stub, because Travis' pypi provider always
    # calls it and will fail if it's missing. It won't actually get
    # bundled into dists.
    - touch setup.py
    deploy:
      provider: pypi
      # `skip-cleanup: true` is required to preserve binary wheel and sdist,
      # built by during `install` step above.
      skip-cleanup: true
      # `skip-existing: true` is required to skip uploading dists, already
      # present in PyPI instead of failing the whole process.
      # This happenes when other CI (AppVeyor etc.) has already uploaded
      # the very same dist (usually sdist).
      skip-existing: true
      user: &pypi-user @token
      password: &pypi-password
        # Encrypt with `travis encrypt -r python/cherry-picker --api-endpoint 'https://api.travis-ci.com/'`
        secure: >-
          aOzHY6j79JqA8/RyNH3akuaeTs0wcDoto3jok+VhbeyIcWEhCI/aqcvDLA7Ld/8p3lQX1JUUWwOyHCEx3UDSDWug/HogbVE5KTT7A+p6gu0ojEXylflOZm6d9E2Ee/VGLXFRISSYQ+Siv8lHqJ1DQ1sUjmmq9rvtdputmRWiJUo1ONfB7eJAiLP/aPF6jn3bUF6dHnOa5lcwjMLypl9v4g4iJsuHFztZIx02NS/Jdh/njDeAQfF8Dx5aG045fAxXd1Nz+Nx2nJUUqUWE5d8RiGTi2nDXTt2f6okZrEDXBsX369yvFED7JTVm7PxeXc7e7r/pB7xseZi5+PeiHZuSYYNOJ9M/sV6Nycjnu8xOKmKEATX0RReS2381k+0SumcoDAH5RYmGlzKrsjEQSJVNPETSnOUqQMuYxze7VIH/ok8aMHa3k38EG3nC/bfT4b38csDbp3lvN7AaWn3OWg2VOdXygOuAIPMt2GfPgY+3EmH7PhtKkIOuD8+2t8LQJ2BgwLa7j91vIFuTfewPjK4AX6YBq6wPLeh44rpXE6/oZhvia0CDgRKPVU13055i3bME/9sjIX5WQigw29h05uI+wEGqNaYu1tI1lbR1qDb8K07xPGAEkjfAbwitQ4y+JcSlIk/R1x3inxlfkw31ceQqe4szaZ/qOD4M5GxRu22lAHg=
      on:
        tags: true
        all_branches: true
