conditions: v1

git:
  depth: false


dist: focal
cache: pip


language: python
python:
- "3.9"
- "3.8"
- "3.7"
- "3.6"

matrix:
  allow_failures:
    - python: "nightly"
      dist: focal

install:
- python -m pip install --upgrade flit
- python -m pip install --upgrade pip
- flit install

script:
- pytest


jobs:
  include:
  - name: Python 3.7 under Windows
    os: windows
    language: sh
    python: "3.7"
    before_install:
    - choco install python --version 3.7
    env:
      PATH: >-
        /c/Python37:/c/Python37/Scripts:$PATH

  - name: Publish dists to production PyPI
    stage: Publish dists to PYPI
    if: tag IS present
    python: "3.7"
    script:
    - flit build
    before_deploy:
    # Add an empty setup.py stub, because Travis' pypi provider always
    # calls it and will fail if it's missing. It won't actually get
    # bundled into dists.
    - touch setup.py
    deploy:
      provider: pypi
      # `skip-cleanup: true` is required to preserve binary wheel and sdist,
      # built by during `install` step above.
      skip-cleanup: true
      # `skip-existing: true` is required to skip uploading dists, already
      # present in PyPI instead of failing the whole process.
      # This happens when other CI (AppVeyor etc.) has already uploaded
      # the very same dist (usually sdist).
      skip-existing: true
      user: &pypi-user core-workflow
      password: &pypi-password
        secure: >-
          py1y8+zVdvsSMj9DFtliu/GRsvgdRFGN4Itp2IYk1gZDhBVMWfZtLdeYcopbdK7rDSfO2pSfYqLeHZ/aQsPg+DIlaK3iseZNvn1U7OBpxdRiNMigg+0HBecK6BCRKZnchm2tw3B3cRvmRpa1Bol5L23tP7ANrFyixS0VLrlA8OoR7JBBsL8v1HE8867nxbvskROL3e1u2g1WLaWov+P2nus0ISp+cMveI8AqFQeOsDynKFLmcwCggXNhl1AMQoS6+f3QOTPRRkG68u4j3yzR+L3kBfqIfExS2pr3XMj73MpVbluxuNAgs0y62IOL3bhZW59wp9MmHyZxMz80qCHqSMNCzcAL5F0QlgT7zZiQoMiNimfiWlCCk3IEN6WmBiHo+C37GBW8sqdfqk0sY3ixsm76AL27cjHKUMUlS4hNSbhyhimzOpAtjWJN20NyzGWOI8EU+X9yVOAaV245pAN3jsW6vS4Dpng0nOFztKX/XPN3Ic9Plq1SJG9SxfCKLL/gA6IW6rSF7FAd1PaeLQTIHy/0EfjxnSj1G8b50FtOhgCBNgjF5R3P3N3+CZTAmzLkC3szPuFpQPMNT3/O58tcmMvS0w99QRJHCdbFb5ugv6sQSToW6eMF9mOuqXf0DPJzX9kbu7/bnjHGUdmTrCWHizmUVjqW5PnRfkmG1FyqOIw=

      on:
        tags: true
        all_branches: true
